name: Api Gateway CI
on:
  push:
    paths:
      - 'api-gateway/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'api-gateway/**'
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build with Maven & Docker build
      run: |
        cd ./api-gateway
        mvn -B package --file pom.xml
        TAG="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
        docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag davideventrigliaswd/ecommerce-demo-api-gateway:$TAG .
        docker push davideventrigliaswd/ecommerce-demo-api-gateway:$TAG
