name: Api Gateway CICD
on:
  push:
    paths:
      - 'api-gateway/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'api-gateway/**'
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        queries: +security-and-quality
    # Manual build 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: |
        cd ./api-gateway
        mvn -B package --file pom.xml
    # Code Analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"

  build:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build with Maven & Docker build
      run: |
        cd ./api-gateway
        export DT=$(date +%s)
        mvn -B package --file pom.xml
        docker build . --tag davideventrigliaswd/ecommerce-demo-api-gateway:$DT
        docker push davideventrigliaswd/ecommerce-demo-api-gateway:$DT
        
