name: Api Gateway CICD
on:
  push:
    paths:
      - 'api-gateway/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'api-gateway/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build with Maven & Docker build
      run: |
        cd ./api-gateway
        mvn -B package --file pom.xml
        docker build . --tag davideventrigliaswd/ecommerce-demo-api-gateway:latest
        docker push davideventrigliaswd/ecommerce-demo-api-gateway:latest
# - name: Extract metadata (tags, labels) for Docker
#   id: meta
#   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#   with:
#     images: davideventrigliaswd/ecommerce-demo-api-gateway
# - name: Build and push Docker image
#   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#   with:
#     context: .
#     push: true
#     tags: ${{ steps.meta.outputs.tags }}
#     labels: ${{ steps.meta.outputs.labels }}
        
