name: Api Gateway CICD
on:
  push:
    paths:
      - 'api-gateway/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'api-gateway/**'
    branches: [ "main" ]

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Enter the folder
      run: cd api-gateway
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Enter the folder
      run: cd api-gateway
    - name: Build the Docker image
      run: docker build . --tag davideventrigliaswd/ecommerce-demo-api-gateway:$(date +%s)
