name: Naming Server CI
on:
  push:
    paths:
      - 'naming-server/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'naming-server/**'
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build with Maven & Docker build
      run: |
        cd ./naming-server
        mvn -B package --file pom.xml
        TAG="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
        docker build . --tag davideventrigliaswd/ecommerce-demo-naming-server:$TAG
        docker push davideventrigliaswd/ecommerce-demo-naming-server:$TAG
