name: Order Microservice CI

env:
  MICROSERVICE_NAME: order-microservice
  REPO_NAME: ${{ github.event.repository.name }}
  DOCKER_OWNER_NAME: davideventrigliaswd

on:
  push:
    paths:
      - 'order-microservice/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'order-microservice/**'
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build with Maven & Docker build
      run: |
        cd ./${{ env.MICROSERVICE_NAME }}
        mvn -B package --file pom.xml
        TAG="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
        docker build . --tag ${{ env.DOCKER_OWNER_NAME }}/${{ env.REPO_NAME }}-${{ env.MICROSERVICE_NAME }}:$TAG
        docker push ${{ env.DOCKER_OWNER_NAME }}/${{ env.REPO_NAME }}-${{ env.MICROSERVICE_NAME }}:$TAG
