name: Static Code Scan
on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        queries: +security-and-quality
    # Manual build 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: |
        cd ./api-gateway
        mvn -B package --file pom.xml
        cd ..
        cd ./order-microservice
        mvn -B package --file pom.xml
        cd ..
        cd ./user-microservice
        mvn -B package --file pom.xml
        cd ..
        cd ./product-microservice
        mvn -B package --file pom.xml
        cd ..
    # Code Analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
